// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkmexsljhbtwfgxeuqnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrbWV4c2xqaGJ0d2ZneGV1cW56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3ODQ5MDQsImV4cCI6MjA2NTM2MDkwNH0.ludqkeGs_QylOlSWS_G3ntzheMiUVy3_g1lCxi5a9OA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);